var worldBorders = {
'Sierra Leone ': ['Guinea','Liberia'],
'Rwanda ': ['Tanzania','Uganda','Burundi','Democratic Republic of the Congo'],
'Israel ': ['Jordan','Lebanon','Syria','Egypt'],
'Nigeria ': ['Benin','Cameroon','Chad','Niger'],
'France (St Martin) ': ['Netherlands (Sint Maarten)'],
'Ireland ': ['United Kingdom'],
'Burma ': ['China','India','Laos','Thailand','Bangladesh'],
'Iraq ': ['Jordan','Kuwait','Saudi Arabia','Syria','Turkey','Iran'],
'Slovenia ': ['Austria','Croatia','Hungary','Italy'],
'Lesotho ': ['South Africa'],
'Czech Republic ': ['Germany','Poland','Slovakia','Austria'],
'Argentina ': ['Bolivia','Brazil','Chile','Paraguay','Uruguay'],
'Finland ': ['Norway','Russia','Sweden'],
'San Marino ': ['Italy'],
'Cyprus ': ['United Kingdom (Sovereign Base Areas)'],
'Democratic Republic of the Congo ': ['Rwanda','Sudan','Tanzania','Uganda','Zambia','Angola','Central African Republic','Burundi','Congo'],
'Honduras ': ['Nicaragua','El Salvador','Guatemala'],
'Indonesia ': ['Malaysia','Papua New Guinea','East Timor'],
'Azerbaijan (Nakhichevan) ': ['Turkey'],
'Gibraltar ': ['Spain'],
'Greece ': ['Macedonia','Turkey','Albania','Bulgaria'],
'United Kingdom (Sovereign Base Areas) ': ['Cyprus'],
'Benin ': ['Burkina Faso','Niger','Nigeria','Togo'],
'Dominican Republic ': ['Haiti'],
'Eritrea ': ['Ethiopia','Sudan','Djibouti'],
'Western Sahara ': ['Algeria','Mauritania','Morocco'],
'Uganda ': ['Democratic Republic of the Congo','Kenya','Rwanda','Sudan','Tanzania'],
'Chile ': ['Peru','Argentina','Bolivia'],
'Malawi ': ['Mozambique','Tanzania','Zambia'],
'Moldova ': ['Romania','Ukraine'],
'North Korea ': ['Russia','South Korea','China'],
'Armenia ': ['Azerbaijan','Georgia','Iran','Turkey'],
'Azerbaijan ': ['Georgia','Iran','Russia','Armenia'],
'Burkina Faso ': ['Ghana','Ivory Coast','Mali','Niger','Togo','Benin'],
'Mozambique ': ['South Africa','Swaziland','Tanzania','Zambia','Zimbabwe','Malawi'],
'Jordan ': ['Saudi Arabia','Syria','Iraq','Israel'],
'Canada ': ['United States of America'],
'Botswana ': ['Namibia','South Africa','Zimbabwe'],
'Liberia ': ['Sierra Leone','Guinea','Ivory Coast'],
'Congo ': ['Democratic Republic of the Congo','Gabon','Angola (Cabinda)','Cameroon','Central African Republic'],
'France ': ['Germany','Italy','Luxembourg','Monaco','Spain','Switzerland','Andorra','Belgium'],
'Ivory Coast ': ['Liberia','Mali','Burkina Faso','Ghana','Guinea'],
'Panama ': ['Colombia','Costa Rica'],
'Macedonia ': ['Serbia & Montenegro','Albania','Bulgaria','Greece'],
'Switzerland ': ['Austria','France','Germany','Italy','Liechtenstein'],
'Russia ': ['Ukraine','Azerbaijan','Belarus','China','Estonia','Finland','Georgia','Kazakhstan','Latvia','Mongolia','North Korea','Norway'],
'Peru ': ['Bolivia','Brazil','Chile','Colombia','Ecuador'],
'Bhutan ': ['China','India'],
'Guinea ': ['Guinea Bissau','Ivory Coast','Liberia','Mali','Senegal','Sierra Leone'],
'Malaysia ': ['Thailand','Brunei','Indonesia'],
'Zimbabwe ': ['Botswana','Mozambique','South Africa','Zambia'],
'Zambia ': ['Zimbabwe','Angola','Democratic Republic of the Congo','Malawi','Mozambique','Namibia','Tanzania'],
'Venezuela ': ['Brazil','Colombia','Guyana'],
'Sweden ': ['Finland','Norway'],
'Surinam ': ['Brazil','French Guiana','Guyana'],
'Albania ': ['Greece','Macedonia','Serbia & Montenegro'],
'Libya ': ['Niger','Sudan','Tunisia','Algeria','Chad','Egypt'],
'Kyrgyzstan ': ['Tajikistan','Uzbekistan','China','Kazakhstan'],
'Angola (Cabinda) ': ['Congo'],
'Brazil ': ['Colombia','French Guiana','Guyana','Paraguay','Peru','Surinam','Uruguay','Venezuela','Argentina','Bolivia'],
'Bangladesh ': ['Burma','India'],
'Netherlands ': ['Belgium','Germany'],
'Senegal ': ['Gambia','Guinea Bissau','Guinea','Mali','Mauritania'],
'Portugal ': ['Spain'],
'Lithuania ': ['Poland','Russia (Kaliningrad)','Belarus','Latvia'],
'Nicaragua ': ['Costa Rica','Honduras'],
'Mexico ': ['United States of America','Belize','Guatemala'],
'Belarus ': ['Latvia','Lithuania','Poland','Russia','Ukraine'],
'Costa Rica ': ['Nicaragua','Panama'],
'Pakistan ': ['Afghanistan','China','India','Iran'],
'Namibia ': ['South Africa','Zambia','Angola','Botswana'],
'Angola ': ['Democratic Republic of the Congo','Namibia','Zambia'],
'Yemen ': ['Oman','Saudi Arabia'],
'United Kingdom ': ['Ireland'],
'Turkey ': ['Armenia','Azerbaijan (Nakhichevan)','Bulgaria','Georgia','Greece','Iran','Iraq','Syria'],
'Tunisia ': ['Algeria','Libya'],
'Papua New Guinea ': ['Indonesia'],
'Croatia ': ['Hungary','Serbia & Montenegro','Slovenia','Bosnia Herzegovina'],
'Equatorial Guinea ': ['Gabon','Cameroon'],
'El Salvador ': ['Guatemala','Honduras'],
'Uruguay ': ['Argentina','Brazil'],
'Italy ': ['San Marino','Slovenia','Switzerland','Vatican City','Austria','France'],
'Monaco ': ['France'],
'Egypt ': ['Israel','Libya','Sudan'],
'Spain ': ['Andorra','France','Gibraltar','Portugal'],
'Poland ': ['Russia (Kaliningrad)','Slovakia','Ukraine','Belarus','Czech Republic','Germany','Lithuania'],
'Djibouti ': ['Eritrea','Ethiopia','Somalia'],
'Kuwait ': ['Saudi Arabia','Iraq'],
'Afghanistan ': ['China','Iran','Pakistan','Tajikistan','Turkmenistan','Uzbekistan'],
'Chad ': ['Libya','Niger','Nigeria','Sudan','Cameroon','Central African Republic'],
'Germany ': ['Luxembourg','Netherlands','Poland','Switzerland','Austria','Belgium','Czech Republic','Denmark','France'],
'Estonia ': ['Latvia','Russia'],
'Cameroon ': ['Central African Republic','Chad','Congo','Equatorial Guinea','Gabon','Nigeria'],
'Central African Republic ': ['Chad','Congo','Democratic Republic of the Congo','Sudan','Cameroon'],
'Morocco ': ['Spain (Ceuta and Melilla)','Western Sahara','Algeria'],
'Uzbekistan ': ['Afghanistan','Kazakhstan','Kyrgyzstan','Tajikistan','Turkmenistan'],
'South Africa ': ['Swaziland','Zimbabwe','Botswana','Lesotho','Mozambique','Namibia'],
'Slovakia ': ['Ukraine','Austria','Czech Republic','Hungary','Poland'],
'Laos ': ['Thailand','Vietnam','Burma','Cambodia','China'],
'Brunei ': ['Malaysia'],
'Latvia ': ['Lithuania','Russia','Belarus','Estonia'],
'Ukraine ': ['Belarus','Hungary','Moldova','Poland','Romania','Russia','Slovakia'],
'Syria ': ['Turkey','Iraq','Israel','Jordan','Lebanon'],
'East Timor ': ['Indonesia'],
'South Korea ': ['North Korea'],
'Russia (Kaliningrad) ': ['Lithuania','Poland'],
'Guatemala ': ['Honduras','Mexico','Belize','El Salvador'],
'Luxembourg ': ['Belgium','France','Germany'],
'Gabon ': ['Cameroon','Congo','Equatorial Guinea'],
'Austria ': ['Czech Republic','Germany','Hungary','Italy','Liechtenstein','Slovakia','Slovenia','Switzerland'],
'Bosnia Herzegovina ': ['Croatia','Serbia & Montenegro'],
'Turkmenistan ': ['Uzbekistan','Afghanistan','Iran','Kazakhstan'],
'Tanzania ': ['Uganda','Zambia','Burundi','Democratic Republic of the Congo','Kenya','Malawi','Mozambique','Rwanda'],
'Serbia & Montenegro ': ['Albania','Bosnia Herzegovina','Bulgaria','Croatia','Hungary','Macedonia','Romania'],
'Qatar ': ['Saudi Arabia'],
'Colombia ': ['Ecuador','Panama','Peru','Venezuela','Brazil'],
'French Guiana ': ['Surinam','Brazil'],
'Nepal ': ['China','India'],
'Tajikistan ': ['Uzbekistan','Afghanistan','China','Kyrgyzstan'],
'Romania ': ['Serbia & Montenegro','Ukraine','Bulgaria','Hungary','Moldova'],
'Mongolia ': ['Russia','China'],
'Mali ': ['Mauritania','Niger','Senegal','Algeria','Burkina Faso','Guinea','Ivory Coast'],
'Vatican City ': ['Italy'],
'Mauritania ': ['Senegal','Western Sahara','Algeria','Mali'],
'Thailand ': ['Burma','Cambodia','Laos','Malaysia'],
'Haiti ': ['Dominican Republic'],
'Niger ': ['Nigeria','Algeria','Benin','Burkina Faso','Chad','Libya','Mali'],
'Bulgaria ': ['Greece','Macedonia','Romania','Serbia & Montenegro','Turkey'],
'Netherlands (Sint Maarten) ': ['France (St Martin)'],
'Togo ': ['Benin','Burkina Faso','Ghana'],
'Paraguay ': ['Argentina','Bolivia','Brazil'],
'Burundi ': ['Democratic Republic of the Congo','Rwanda','Tanzania'],
'Kazakhstan ': ['Kyrgyzstan','Russia','Turkmenistan','Uzbekistan','China'],
'Liechtenstein ': ['Switzerland','Austria'],
'Vietnam ': ['Cambodia','China','Laos'],
'United States of America ': ['Canada','Mexico'],
'Somalia ': ['Djibouti','Ethiopia','Kenya'],
'Cambodia ': ['Laos','Thailand','Vietnam'],
'Swaziland ': ['Mozambique','South Africa'],
'Saudi Arabia ': ['United Arab Emirates','Yemen','Iraq','Jordan','Kuwait','Oman','Qatar'],
'Norway ': ['Russia','Sweden','Finland'],
'Belgium ': ['France','Germany','Luxembourg','Netherlands'],
'China ': ['India','Kazakhstan','Kyrgyzstan','Laos','Mongolia','Nepal','North Korea','Pakistan','Russia','Tajikistan','Vietnam','Afghanistan','Bhutan','Burma'],
'Hungary ': ['Romania','Serbia & Montenegro','Slovakia','Slovenia','Ukraine','Austria','Croatia'],
'Lebanon ': ['Syria','Israel'],
'India ': ['Nepal','Pakistan','Bangladesh','Bhutan','Burma','China'],
'United Arab Emirates ': ['Oman','Saudi Arabia'],
'Spain (Ceuta and Melilla) ': ['Morocco'],
'Andorra ': ['France','Spain'],
'Ghana ': ['Ivory Coast','Togo','Burkina Faso'],
'Georgia ': ['Russia','Turkey','Armenia','Azerbaijan'],
'Gambia ': ['Senegal'],
'Guyana ': ['Surinam','Venezuela','Brazil'],
'Bolivia ': ['Brazil','Chile','Paraguay','Peru','Argentina'],
'Ethiopia ': ['Kenya','Somalia','Sudan','Djibouti','Eritrea'],
'Kenya ': ['Somalia','Sudan','Tanzania','Uganda','Ethiopia'],
'Ecuador ': ['Peru','Colombia'],
'Iran ': ['Iraq','Pakistan','Turkey','Turkmenistan','Afghanistan','Armenia','Azerbaijan'],
'Guinea Bissau ': ['Senegal','Guinea'],
'Belize ': ['Guatemala','Mexico'],
'Denmark ': ['Germany'],
'Sudan ': ['Uganda','Central African Republic','Chad','Democratic Republic of the Congo','Egypt','Eritrea','Ethiopia','Kenya','Libya'],
'Oman ': ['Saudi Arabia','United Arab Emirates','Yemen'],
'Algeria ': ['Libya','Mali','Mauritania','Morocco','Niger','Tunisia','Western Sahara']
}